### ISSUE TITLE
can't run the demo.cpp

### ISSUE THREAD

**Issue by zhiiiyang** [ypan1988/roptim#1]
Hi, thank you for making this package which might potentially facilitate one of the projects that I am working on. There is one thing that I couldn't follow, which is to reproduce the example described in the README.md. I downloaded the demo.cpp and try to run the following R code. However, it gave me lots of error messages, which do not fit here. 

```R
library(Rcpp)
sourceCpp("~/demo.cpp") # you may need to change the directory
rosen_bfgs()
```

Please let me know if this is the right way to execute the rcpp code. Thank you!

**Comment by ypan1988** [comment]
Hi, Could you please try to install both Rcpp and roptim, and run the code again. If you still have the same error, please attach the error message so that I can find out what the problem is. Thanks!

**Comment by ypan1988** [comment]
By the way, if you are going to use this package in your own R package rather than "R code with cpp file". Please have a look at the following package:
https://github.com/ypan1988/jmcm
which uses the BFGS algorithm in package roptim for optimization.

**Comment by zhiiiyang** [comment]
Thank you for getting back to me. I still couldn't get things running after reinstalling `Rcpp` and `roptim`. The very first error message starts with the following:
```R
clang: error: unsupported option '-fopenmp'
```
This error message appearred when I tried to install the GitHub version of your pacakge too. 
Thank you for the help again!

**Comment by ypan1988** [comment]
Please install the updated GitHub version of this package and try again as I have just disabled the use of openmp.

**Comment by zhiiiyang** [comment]
Cool. The error messages from installation is gone and here are the ones that left. 

```R
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [roptim.so] Error 1
ERROR: compilation failed for package ‘roptim’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/roptim’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/roptim’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/qh/n3bqs6vj2x76jjtgd6z362lc0000gn/T//RtmpGBI0mc/file10d335fb8080/roptim_0.1.2.tar.gz’ had non-zero exit status
```

**Comment by ypan1988** [comment]
Check this:
https://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks--lgfortran-and--lquadmath-error/

**Comment by ypan1988** [comment]
> Cool. The error messages from installation is gone and here are the ones that left.
> 
> ```r
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
> ld: library not found for -lgfortran
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [roptim.so] Error 1
> ERROR: compilation failed for package ‘roptim’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/roptim’
> * restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/roptim’
> Error in i.p(...) : 
>   (converted from warning) installation of package ‘/var/folders/qh/n3bqs6vj2x76jjtgd6z362lc0000gn/T//RtmpGBI0mc/file10d335fb8080/roptim_0.1.2.tar.gz’ had non-zero exit status
> ```

problem solved?

**Comment by zhiiiyang** [comment]
It worked for my desktop. I guess something is going on with my MacBook which I will figure it out later. Thank you for all the help!
