### ISSUE TITLE
Specify intolerable parameter set in fit function

### ISSUE THREAD

**Issue by SachaEpskamp** [ypan1988/roptim#3]
Hi Yi Pan,

Thank you very much for your earlier help! I was encountering one more problem I hope you could help me with. In optimization, I require parameters to form positive definite matrices. However, sometimes the optimizer would go to a parameter value that would lead to non positive definite matrices. I was wondering if there is some way to specify when the parameters are in a non tolerable space? I tried building in a simple if statement in the fit function that returns `NA_REAL` or a very large number, but the first solution gives the message:

```
 L-BFGS-B needs finite values of 'fn'
```

And the second solution seems to work but leads to poor parameter estimates.

Best, Sacha

**Comment by ypan1988** [comment]
Hi, Sacha.

If you have obtained the parameter estimations and the corresponding matrix is not positive definite, you can 
+ find the nearest positive definite matrix (https://nhigham.com/2013/02/13/the-nearest-correlation-matrix/)
+ use numerical approximation of the matrix. e.g., class Functor has a member function Hessian() which will call ApproximateHessian(par, hess) automatically if it is not defined.
+ if you are using L-BFGS-B and fail to find parameter estimation as fn become extremely large, maybe the starting value is not good enough or the underlying algorithm is not well implemented. One thing worth trying is that use another optimization algorithm to get a better starting point.

With best wishes

Yi

**Comment by SachaEpskamp** [comment]
Thanks!
