### ISSUE TITLE
NOTE in R devel check

### ISSUE THREAD

**Issue by SachaEpskamp** [ypan1988/roptim#4]
Hi Yi,

I am getting my package ready for CRAN and get the following note when running the check on R-devel:
```
File ‘psychonetrics/libs/psychonetrics.so’:
  Found ‘_ZSt4cout’, possibly from ‘std::cout’ (C++)
    Object: ‘04_generalfit_psychonetrics_BFGS.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.
```

I don't see any reference to cout or so in the [corresponding code](https://github.com/SachaEpskamp/psychonetrics/blob/master/src/04_generalfit_psychonetrics_BFGS.cpp) though. I was wondering if this NOTE is perhaps due to the roptim import here?

**Comment by ypan1988** [comment]
Hi, Sacha.

Sorry for this -- I was using std::cout for some debug output and will remove them today/tomorrow.

**Comment by SachaEpskamp** [comment]
Great, thanks!
