### ISSUE TITLE
Use of numerical gradient

### ISSUE THREAD

**Issue by teng-gao** [ypan1988/roptim#5]
Hi, 

I have a custom function for which there is no analytical gradient that I can find. Is it still possible to use this package to do optimization in Rcpp (without defining a gradient function)?

Thanks,
Teng

**Comment by ypan1988** [comment]
Yes, you can use Nelder-Mead.

Yi

________________________________
From: ***@***.*** ***@***.***>
Sent: 26 June 2022 21:56:35
To: ypan1988/roptim
Cc: Subscribed
Subject: [ypan1988/roptim] Use of numerical gradient (Issue #5)


Hi,

I have a custom function for which there is no analytical gradient that I can find. Is it still possible to use this package to do optimization in Rcpp (without defining a gradient function)?

Thanks,
Teng

**Comment by teng-gao** [comment]
Hi Yi,

Thanks for the reply. To be more precise, I'm trying to replicate the behavior of the below code in R, where L-BFGS-B is used, but no gradient function is provided.

```
optim(
    start, 
    function(x) {f(x)},
    method = 'L-BFGS-B',
    lower = lower,
    upper = upper,
    hessian = TRUE
)
```

Thanks,
Teng

**Comment by ypan1988** [comment]
Yes, it is possible and please check the following paper:
https://cran.r-project.org/web/packages/roptim/vignettes/article.pdf

Yi

**Comment by teng-gao** [comment]
Got it - this is super useful for our work! I'm trying to parallelize many individual `optim` calls using RcppParallel. Do you think `Roptim` would be thread-safe enough to do so?

**Comment by ypan1988** [comment]
Sorry, I am not very sure about this. But my understanding is that if you are calling optim in parallel, that means you are calling the underlying C functions of optim in parallel. Roptim is simply a wrapper of the C functions to make it easier to write code in C++, so maybe create a separate Roptim object for each thread?! Do consult someone with more experience with parallel programming.
