### ISSUE TITLE
Citation for the package?

### ISSUE THREAD

**Issue by privefl** [ypan1988/roptim#8]
The vignette looks like a manuscript.
Was it published somewhere that I could cite?

**Comment by ypan1988** [comment]
No, here is what I find on google scholar (feel free if you would like to change anything to make it a bit more formal):
```
@article{pan2020roptim,
  title={roptim: An R Package for General Purpose Optimization with C++},
  author={Pan, Yi and Pan, Jianxin},
  journal={R package version},
  year={2020}
}
```
I left academia, and the paper might not be published in a short time. (But I will probably try to submit it to JSS/R journal after making some necessary changes when I am available). Anyway, good luck to your research and thanks again for your contribution to the package!

**Comment by privefl** [comment]
Another loss for academia :-(
