### ISSUE TITLE
passing other arguments

### ISSUE THREAD

**Issue by mengqi00** [ypan1988/roptim#9]
Hi, I want to pass other arguments to the roptim in Rcpp but I don't know how to do that.
For example, I want to do the same thing in rcpp as the following in R's optim():

> optim(par=r0, fn=fn, gr=gr, X=X, time=time, q=q, k=k, method = 'L-BFGS-B')

Do you know how could I do that? Thank you very much!

**Comment by ypan1988** [comment]
This can be easily done by the following steps:
1. define the other variables as data members of the class;
2. pass the arguments when creating the object with the constructor.
I would suggest checking the example on page 14 (sec 3.2) of the following paper:
https://cran.r-project.org/web/packages/roptim/vignettes/article.pdf
Thanks.

**Comment by mengqi00** [comment]
Thank you! This makes sense!
